#!/usr/bin/env python3
"""
Regenerate INVENTORY.md by scanning all content.md files in the reference library.

Usage:
  python tools/regenerate_inventory.py
  REFERENCE_LIBRARY_ROOT=/path/to/library python tools/regenerate_inventory.py

Library location resolution (in priority order):
  1. REFERENCE_LIBRARY_ROOT environment variable
  2. Parent directory of this script (legacy: tools/ inside the library)
"""

import os
import re
from pathlib import Path
from datetime import date


def _resolve_library_root() -> Path:
    env = os.environ.get("REFERENCE_LIBRARY_ROOT")
    if env:
        return Path(env).expanduser().resolve()
    return Path(__file__).parent.parent


LIBRARY_ROOT = _resolve_library_root()

CATEGORY_ORDER = [
    "ai-agents",
    "ml-oreilly",
    "app-dev-mobile",
    "web-dev",
    "shells-scripting",
    "linux-no-starch",
    "godot-game-dev",
    "data-science",
    "hacking-security",
]

CATEGORY_LABELS = {
    "ai-agents":        "AI Agents & LLMs",
    "ml-oreilly":       "ML / O'Reilly",
    "app-dev-mobile":   "App Dev & Mobile",
    "web-dev":          "Web Dev",
    "shells-scripting": "Shells & Scripting",
    "linux-no-starch":  "Linux / No Starch",
    "godot-game-dev":   "Godot Game Dev",
    "data-science":     "Data Science",
    "hacking-security": "Hacking & Security",
}


def parse_frontmatter(text: str) -> dict:
    """Extract YAML frontmatter key/value pairs. Simple parser — no pyyaml needed."""
    if not text.startswith("---"):
        return {}
    end = text.find("\n---", 3)
    if end == -1:
        return {}
    block = text[4:end]
    result = {}
    for line in block.splitlines():
        if ":" not in line:
            continue
        key, _, val = line.partition(":")
        key = key.strip()
        val = val.strip()
        # Unwrap quoted strings
        if val.startswith('"') and val.endswith('"'):
            val = val[1:-1]
        elif val.startswith("'") and val.endswith("'"):
            val = val[1:-1]
        # Parse boolean
        if val.lower() == "true":
            val = True
        elif val.lower() == "false":
            val = False
        result[key] = val
    return result


def count_images(book_dir: Path) -> int:
    images_dir = book_dir / "images"
    if not images_dir.exists():
        return 0
    return sum(1 for f in images_dir.iterdir() if f.is_file())


def scan_library() -> dict:
    """Returns {category: [book_info, ...]} sorted by category order."""
    books_by_category: dict[str, list] = {cat: [] for cat in CATEGORY_ORDER}

    for content_path in sorted(LIBRARY_ROOT.rglob("content.md")):
        # Skip anything inside tools/ or _maps/ or hidden dirs
        parts = content_path.relative_to(LIBRARY_ROOT).parts
        if parts[0].startswith("_") or parts[0] == "tools":
            continue

        category = parts[0]
        if category not in books_by_category:
            books_by_category[category] = []

        slug = parts[1] if len(parts) > 1 else "unknown"
        book_dir = content_path.parent
        text = content_path.read_text(encoding="utf-8", errors="replace")
        fm = parse_frontmatter(text)

        size_kb = content_path.stat().st_size / 1024
        image_count = count_images(book_dir)
        has_insights = (book_dir / "INSIGHTS.md").exists()

        books_by_category[category].append({
            "slug": slug,
            "title": fm.get("title", slug),
            "author": fm.get("author", ""),
            "size_kb": size_kb,
            "images": image_count,
            "insights": has_insights,
            "topics": fm.get("topics", ""),
            "projects": fm.get("projects", ""),
        })

    # Sort books within each category by title
    for cat in books_by_category:
        books_by_category[cat].sort(key=lambda b: b["title"].lower())

    return books_by_category


def render_inventory(books_by_category: dict) -> str:
    today = date.today().strftime("%Y-%m-%d")
    total_books = sum(len(v) for v in books_by_category.values())
    total_insights = sum(
        sum(1 for b in books if b["insights"])
        for books in books_by_category.values()
    )

    lines = [
        f"# Reference Library — Book Inventory",
        f"> Last updated: {today} | Generated by regenerate_inventory.py",
        f"> **{total_books} books extracted** | **{total_insights} with INSIGHTS.md**",
        "",
        "---",
        "",
        "## Legend",
        "- `[I]` — INSIGHTS.md extracted",
        "- Size = Markdown file size in KB",
        "- Imgs = number of extracted images",
        "",
        "---",
        "",
    ]

    for cat in CATEGORY_ORDER:
        books = books_by_category.get(cat, [])
        if not books:
            continue

        label = CATEGORY_LABELS.get(cat, cat)
        cat_insights = sum(1 for b in books if b["insights"])
        lines.append(f"## {label} (`{cat}`) — {len(books)} books, {cat_insights} with insights")
        lines.append("")
        lines.append("| Title | Author | Size KB | Imgs | Insights |")
        lines.append("|---|---|---:|---:|:---:|")

        for b in books:
            insights_marker = "✓" if b["insights"] else ""
            author = b["author"] or "—"
            lines.append(
                f"| {b['title']} | {author} | {b['size_kb']:.1f} | {b['images']} | {insights_marker} |"
            )

        lines.append("")
        total_kb = sum(b["size_kb"] for b in books)
        total_imgs = sum(b["images"] for b in books)
        lines.append(f"**Totals:** {len(books)} books | {total_kb:.0f} KB | {total_imgs} images")
        lines.append("")
        lines.append("---")
        lines.append("")

    # Summary table
    lines.append("## Summary")
    lines.append("")
    lines.append("| Category | Books | Insights | Total KB | Total Images |")
    lines.append("|---|---:|---:|---:|---:|")

    grand_books = grand_kb = grand_imgs = grand_insights = 0
    for cat in CATEGORY_ORDER:
        books = books_by_category.get(cat, [])
        if not books:
            continue
        n = len(books)
        ni = sum(1 for b in books if b["insights"])
        kb = sum(b["size_kb"] for b in books)
        imgs = sum(b["images"] for b in books)
        label = CATEGORY_LABELS.get(cat, cat)
        lines.append(f"| {label} | {n} | {ni} | {kb:.0f} | {imgs} |")
        grand_books += n
        grand_kb += kb
        grand_imgs += imgs
        grand_insights += ni

    lines.append(f"| **TOTAL** | **{grand_books}** | **{grand_insights}** | **{grand_kb:.0f}** | **{grand_imgs}** |")
    lines.append("")

    return "\n".join(lines)


def main():
    print("Scanning library...")
    books_by_category = scan_library()
    total = sum(len(v) for v in books_by_category.values())
    print(f"Found {total} books across {len([c for c in CATEGORY_ORDER if books_by_category.get(c)])} categories")

    inventory_text = render_inventory(books_by_category)
    output_path = LIBRARY_ROOT / "INVENTORY.md"
    output_path.write_text(inventory_text, encoding="utf-8")
    print(f"Written: {output_path}")

    # Print per-category counts
    for cat in CATEGORY_ORDER:
        books = books_by_category.get(cat, [])
        if books:
            insights = sum(1 for b in books if b["insights"])
            print(f"  {cat}: {len(books)} books, {insights} with insights")


if __name__ == "__main__":
    main()
